config/routes.rb
Rails.application.routes.draw do
	concern :commentable do
		post '/comments' => :create_comment, as: :comments
		delete '/commments/:id' => :destroy_comment, as: :comment
	end

	concern :subscribable do
		get :subscribe
		get :unsubscribe
	end

	root "meta#index"
	scope controller: :meta do
		get '/about' => :about
		get '/contact' => :contact
		get '/terms' => :terms
	end

	scope controller: :session do
		get '/signup' => :signup
		post '/register' => :register
		get '/login' => :login
		post '/authenticate' => :authenticate
		get '/logout' => :logout
		get '/forgot-password' => :forgot_password
		post '/password-reset-request' => :password_reset_request
		get '/password-reset/:sgid' => :password_reset, as: :password_reset
		post '/password-reset/:sgid' => :submit_password_reset
		get '/password-reset-sent' => :password_reset_sent
	end

	scope controller: :home do
		get '/home' => :index
		get '/profile' => :profile
		post '/profile/request_verification' => :request_verification
		post '/profile/confirm_verification' => :confirm_verification
		get '/profile/edit' => :edit_profile
		patch '/profile' => :update_profile
		delete '/profile' => :delete_profile
	end

	resources :locations, param: :name, only: [:index, :show] do
		concerns :subscribable
	end

	resources :events do
		concerns :commentable
	end

	resources :organisations, param: :name do
		concerns :subscribable
		get 'moderators' => :choose_moderators
		post 'moderators' => :update_moderators
		get :apply
		get :leave
		get :invite_members
		post :send_invitations
		get :transfer
		post :begin_transfer
		resources :discussions do
			concerns :commentable
		end
	end

	#Passing registrant status to another user
	get '/organisations/:org_sgid/:user_sgid/accept-transfer' => "organisations#accept_transfer", as: :organisation_accept_transfer
	get '/organisations/:org_sgid/:user_sgid/reject-transfer' => "organisations#reject_transfer", as: :organisation_reject_transfer

	#User applied for membership
	get '/memberships/:sgid/accept_application' => "memberships#accept_application", as: :membership_accept_application
	get '/memberships/:sgid/reject_application' => "memberships#reject_application", as: :membership_reject_application

	#User offerred membership
	get '/memberships/:org_sgid/:user_sgid/accept-invitation' => "memberships#accept_invitation", as: :membership_accept_invitation
	get '/memberships/:org_sgid/:user_sgid/reject-invitation' => "memberships#reject_invitation", as: :membership_reject_invitation

	scope controller: :feedback do
		get '/feedback' => :index
		get '/feedback/general' => :general
		get '/feedback/missing_location' => :location
		post '/feedback/general' => :submit_general
		post '/feedback/missing_location' => :submit_location
	end

	namespace :console, controller: :main do
		root "main#index"

		resources :users
		resources :locations do
			post 'from_csv', on: :collection
			get 'to_csv', on: :collection
		end
		resources :events
		resources :organisations

		get 'config' => :config_index
		get 'config/branding' => :branding
		post 'config/branding' => :update_branding
		post 'config/logo' => :update_logo
		get 'config/map' => :map
		post 'config/map' => :update_map
		get 'config/terms' => :terms
		post 'config/terms' => :update_terms
		get 'config/export' => :export_config
		post 'config/import' => :import_config

		get 'logs/:hours/hours' => :logs, as: 'logs'

		get 'announcement' => :announcement
		post 'announcement' => :submit_announcement
	end
end

# vim: ts=4 sts=4 sw=0 noexpandtab

app/controllers/session_controller.rb
class SessionController < ApplicationController
	include UserHelper

	layout "special", only: [:password_reset_request]
	layout "meta"
	before_action :logged_out_check
	skip_before_action :logged_out_check, only: [:logout]


	def signup
		@subtitle = "Sign Up"
		@user = User.new
		@locations = Location.where(ancestry:nil).order(:name)
	end

	def register
		begin
			@user = User.new
			@user.user_name = params[:user_name]
			@user.real_name = params[:real_name]
			@user.email = params[:email]
			@user.password = params[:password]

			if params[:home_location_id].blank? == false
				@user.home_location = Location.find( params[:home_location_id] )
			end
			@user.priv = 0

			raise DuplicateUser if User.find_by_user_name(params[:user_name])
			raise InvalidPassword if is_invalid_password(params[:password])
			raise BadConfirmation if params[:confirmation] != params[:password]

			@user.save!
			session[:user_id] = @user.id

			ActionLog.create(json: {
				user_name: @user.user_name, user_id: @user.id,
				model: 'user', action: 'create'
			}).save

			redirect_to home_path, flash: {success: "Account created"}
		rescue DuplicateUser => e
			@subtitle = "Sign Up"
			@locations = Location.where(ancestry:nil).order(:name)
			flash.now[:error] = "Account already exist"
			render :signup, status: :forbidden
		rescue InvalidPassword => e
			@subtitle = "Sign Up"
			@locations = Location.where(ancestry:nil).order(:name)
			flash.now[:error] = "Invalid password"
			render :signup, status: :unprocessable_entity
		rescue BadConfirmation => e
			@subtitle = "Sign Up"
			@locations = Location.where(ancestry:nil).order(:name)
			flash.now[:error] = "Bad password confirmation"
			render :signup, status: :unprocessable_entity
		rescue ActiveRecord::RecordNotFound => e
			@subtitle = "Sign Up"
			@locations = Location.where(ancestry:nil).order(:name)
			flash.now[:error] = "Home Location not found"
			render :signup, status: :unprocessable_entity
		rescue ActiveRecord::RecordInvalid => e
			@subtitle = "Sign Up"
			@locations = Location.where(ancestry:nil).order(:name)
			flash.now[:error] = "Could not create account"
			render :signup, status: :unprocessable_entity
		end
	end

	def login
		@subtitle = "Login"
		@user = User.new
	end

	def authenticate
		begin
			@user = User.find_by_user_name! params[:user_name]

			raise InvalidPassword if @user.authenticate(params[:password]) == false

			session[:user_id] = @user.id
			redirect_to home_path, flash: {success: "Successfully logged in"}
		rescue ActiveRecord::RecordNotFound => e
			@subtitle = "Login"
			flash.now[:error] = "Invalid user name or password"
			render :login, status: :forbidden
		rescue InvalidPassword => e
			@subtitle = "Login"
			flash.now[:error] = "Invalid user name or password"
			render :login, status: :forbidden
		end
	end

	def logout
		session[:user_id] = nil
		redirect_to login_path, flash: {success: "Logged out. See you later!"}
	end

	def forgot_password
		@subtitle = "Forgot Password"
	end

	def password_reset_request
		@subtitle = "Forgot Password"

		user = User.find_by_email(params[:email])

		if user != nil
			sgid = user.signed_id(expires_in: 24.hours, purpose: :password_reset)

			UserMailer.password_reset_request(user, sgid).deliver_now
		end

		redirect_to password_reset_sent_path, flash:
			{info: "You will receive an email containing a reset link IF you entered a valid address"}
	end

	def password_reset
		@subtitle = "Reset Password"
	end

	def submit_password_reset
		@subtitle = "Reset Password"

		begin
			raise InvalidPassword if is_invalid_password(params[:password])
			raise BadConfirmation if params[:confirmation] != params[:password]

			@user = User.find_signed! params[:sgid], purpose: :password_reset

			@user.password = params[:password]
			@user.save!

			redirect_to login_path, flash:
				{success: "Your password has been updated"}
		rescue InvalidPassword => e
			redirect_to password_reset_path(params[:sgid]), flash:
				{error: "Invalid password"}
		rescue BadConfirmation => e
			redirect_to password_reset_path(params[:sgid]), flash:
				{error: "Password and confirmation do not match"}
		rescue ActiveSupport::MessageVerifier::InvalidSignature => e
			redirect_to password_reset_path(params[:sgid]), flash:
				{error: "Could not find password-reset code"}
		rescue ActiveRecord::RecordNotFound => e
			redirect_to password_reset_path(params[:sgid]), flash:
				{error: "Could not find user account"}
		rescue ActiveRecord::RecordInvalid => e
			redirect_to password_reset_path(params[:sgid]), flash:
				{error: "Could not update password"}
		end
	end
end

# vim: ts=4 sts=4 sw=0 noexpandtab

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/forgot_password.html.erb
<%= form_with url: password_reset_request_path, method: :post do |f| -%>
	<div class="container">
		<div class="row">
			<%= f.label :email, class: 'col-md-2 col-sm-12' -%>
			<%= f.email_field :email,
				class: 'col-md-5 col-sm-12' -%>
		</div>
	<div class="row">
		<%= f.submit "Request Reset", class: 'col-md-5 col-sm-12 offset-md-2' -%>
	</div>
<%- end -%>

<%
	# vim: ts=4 sts=4 sw=0 noexpandtab
%>

app/views/session/login.html.erb
<%= form_with url: authenticate_path, method: :post do |f| -%>
	<div class="container">
		<div class="row">
			<%= f.label :user_name, class: 'col-md-2 col-sm-12' -%>
			<%= f.text_field :user_name,
				class: 'col-md-5 col-sm-12' -%>
		</div>
	<div class="row">
		<%= f.label :password, class: 'col-md-2 col-sm-12' -%>
		<%= f.password_field :password, class: 'col-md-5 col-sm-12' -%>
	</div>
	<div class="row">
		<%= f.submit "Log In", class: 'col-md-5 col-sm-12 offset-md-2' -%>
	</div>
<%- end -%>

<hr/>

<%= button_to "Forgot your password?", forgot_password_path, method: :get -%>

<%= button_to "Don't have an account yet?", signup_path, method: :get -%>

<%
	# vim: ts=4 sts=4 sw=0 noexpandtab
%>

app/views/session/password_reset.html.erb
<%= form_with url: password_reset_path(params[:sgid]), method: :post do |f| -%>
	<div class="container">
		<div class="row">
			<%= f.label :password, class: 'col-md-2 col-sm-12' -%>
			<%= f.password_field :password, class: 'col-md-5 col-sm-12' -%>
		</div>
		<div class="row">
			<%= f.label :confirmation, class: 'col-md-2 col-sm-12' -%>
			<%= f.password_field :confirmation, class: 'col-md-5 col-sm-12' -%>
		</div>
		<div class="row">
			<%= f.submit "Reset password",
				class: 'col-md-5 col-sm-12 offset-md-2' -%>
		</div>
	</div>
<%- end -%>

<%#
	# vim: ts=4 sts=4 sw=0 noexpandtab
-%>

app/views/session/password_reset_sent.html.erb
<p>
If you entered a valid email address you will receive a link to a password
reset link soon.
</p>

app/views/session/signup.html.erb
<%= form_with url: register_path, method: :post do |f| -%>
	<div class="container">
		<div class="row">
			<%= f.label :user_name, class: 'col-md-2 col-sm-12' -%>
			<%= f.text_field :user_name, class: 'col-md-5 col-sm-12' -%>
		</div>
		<div class="row">
			<%- @user.errors.full_messages_for(:user_name).each do |message| -%>
				<div class="col-5 offset-2"><%= message -%></div>
			<%- end -%>
		</div>
		<div class="row">
			<%= f.label :real_name, class: 'col-md-2 col-sm-12' -%>
			<%= f.text_field :real_name, class: 'col-md-5 col-sm-12' -%>
		</div>
		<div class="row">
			<%- @user.errors.full_messages_for(:real_name).each do |message| -%>
				<div class="col-5 offset-2"><%= message -%></div>
			<%- end -%>
		</div>
		<div class="row">
			<%= f.label :email, class: 'col-md-2 col-sm-12' -%>
			<%= f.text_field :email, class: 'col-md-5 col-sm-12' -%>
		</div>
		<div class="row">
			<%- @user.errors.full_messages_for(:email).each do |message| -%>
				<div class="col-5 offset-2"><%= message -%></div>
			<%- end -%>
		</div>
		<div class="row">
			<%= f.label :password, class: 'col-md-2 col-sm-12' -%>
			<%= f.password_field :password, class: 'col-md-5 col-sm-12' -%>
		</div>
		<div class="row">
			<%- @user.errors.full_messages_for(:password).each do |message| -%>
				<div class="col-5 offset-2"><%= message -%></div>
			<%- end -%>
		</div>
		<div class="row">
			<%= f.label :confirmation, class: 'col-md-2 col-sm-12' -%>
			<%= f.password_field :confirmation, class: 'col-md-5 col-sm-12' -%>
		</div>
		<div class="row">
			<%= f.label :home_location_id, "Home location (optional)", class: '' -%>
			<%= f.collection_select(:home_location_id, @locations, :id, :name,
					{include_blank: true}, {class: 'col-md-5 col-sm-12'}) -%>
		</div>
		<div class="row">
			<%- @user.errors.full_messages_for(:confirmation).each do |message| -%>
				<div class="col-5 offset-2"><%= message -%></div>
			<%- end -%>
		</div>
		<div class="row">
			<div class="col-md-2 col-sm-12">
				I agree to the
				<%= link_to "Terms of Service", terms_path, target: "_blank" -%>
			</div>
			<%= f.check_box :agree, checked: false,
				class: 'col-md-5 col-sm-12' -%>
		</div>
		<div class="row">
			<%= f.submit "Sign up", disabled: true,
				class: 'col-md-5 col-sm-12 offset-md-2' -%>
		</div>
	</div>
<%- end -%>

<script type="module">
	import {$} from "<%= javascript_path "application.js" -%>";

	$(document).ready(function() {
		$('input[type=checkbox]').click(function() {
			if(this.checked){
				$('input[type=submit]').prop('disabled', false);
			} else {
				$('input[type=submit]').prop('disabled', true);
			}
		});
	});
</script>

<hr/>
<%= link_to("Already have an account?", login_path) -%>

<%#
	# vim: ts=4 sts=4 sw=0 noexpandtab
-%>