config/routes.rb
Rails.application.routes.draw do
	concern :commentable do
		post '/comments' => :create_comment, as: :comments
		delete '/commments/:id' => :destroy_comment, as: :comment
	end

	concern :subscribable do
		get :subscribe
		get :unsubscribe
	end

	root "meta#index"
	scope controller: :meta do
		get '/about' => :about
		get '/contact' => :contact
		get '/terms' => :terms
	end

	scope controller: :session do
		get '/signup' => :signup
		post '/register' => :register
		get '/login' => :login
		post '/authenticate' => :authenticate
		get '/logout' => :logout
		get '/forgot-password' => :forgot_password
		post '/password-reset-request' => :password_reset_request
		get '/password-reset/:sgid' => :password_reset, as: :password_reset
		post '/password-reset/:sgid' => :submit_password_reset
		get '/password-reset-sent' => :password_reset_sent
	end

	scope controller: :home do
		get '/home' => :index
		get '/profile' => :profile
		post '/profile/request_verification' => :request_verification
		post '/profile/confirm_verification' => :confirm_verification
		get '/profile/edit' => :edit_profile
		patch '/profile' => :update_profile
		delete '/profile' => :delete_profile
	end

	resources :locations, param: :name, only: [:index, :show] do
		concerns :subscribable
	end

	resources :events do
		concerns :commentable
	end

	resources :organisations, param: :name do
		concerns :subscribable
		get 'moderators' => :choose_moderators
		post 'moderators' => :update_moderators
		get :apply
		get :leave
		get :invite_members
		post :send_invitations
		get :transfer
		post :begin_transfer
		resources :discussions do
			concerns :commentable
		end
	end

	#Passing registrant status to another user
	get '/organisations/:org_sgid/:user_sgid/accept-transfer' => "organisations#accept_transfer", as: :organisation_accept_transfer
	get '/organisations/:org_sgid/:user_sgid/reject-transfer' => "organisations#reject_transfer", as: :organisation_reject_transfer

	#User applied for membership
	get '/memberships/:sgid/accept_application' => "memberships#accept_application", as: :membership_accept_application
	get '/memberships/:sgid/reject_application' => "memberships#reject_application", as: :membership_reject_application

	#User offerred membership
	get '/memberships/:org_sgid/:user_sgid/accept-invitation' => "memberships#accept_invitation", as: :membership_accept_invitation
	get '/memberships/:org_sgid/:user_sgid/reject-invitation' => "memberships#reject_invitation", as: :membership_reject_invitation

	scope controller: :feedback do
		get '/feedback' => :index
		get '/feedback/general' => :general
		get '/feedback/missing_location' => :location
		post '/feedback/general' => :submit_general
		post '/feedback/missing_location' => :submit_location
	end

	namespace :console, controller: :main do
		root "main#index"

		resources :users
		resources :locations do
			post 'from_csv', on: :collection
			get 'to_csv', on: :collection
		end
		resources :events
		resources :organisations

		get 'config' => :config_index
		get 'config/branding' => :branding
		post 'config/branding' => :update_branding
		post 'config/logo' => :update_logo
		get 'config/map' => :map
		post 'config/map' => :update_map
		get 'config/terms' => :terms
		post 'config/terms' => :update_terms
		get 'config/export' => :export_config
		post 'config/import' => :import_config

		get 'logs/:hours/hours' => :logs, as: 'logs'

		get 'announcement' => :announcement
		post 'announcement' => :submit_announcement
	end
end

# vim: ts=4 sts=4 sw=0 noexpandtab

app/controllers/home_controller.rb
require 'securerandom'


class HomeController < ApplicationController
	before_action :logged_in_check
	before_action :load_map_source, only: :index


	def index
		@subtitle = "Home"
		if current_user.home_location
			@lat = current_user.home_location.lat
			@lng = current_user.home_location.lng
		else
			@lat = Rails.configuration.vicinitude[:map_centre][:lat]
			@lng = Rails.configuration.vicinitude[:map_centre][:lng]
		end
		@high_zoom = Rails.configuration.vicinitude[:map_centre][:high_zoom]
		@low_zoom = Rails.configuration.vicinitude[:map_centre][:low_zoom]

		#Add all Neighbourhoods to the map
		@events = {}
		Location.where(ancestry: nil).each do |hood|
			@events[hood] = []
		end

		#Associate events with the neighbourhoods they are in
		now = DateTime.now
		Event.where('end_time > ?', now).each do |event|
			@events[event.location.root] << event
		end
	end

	def profile
		@user = current_user
		@subtitle = "Your profile"

		@loc_subs = Subscription.where(
			user: current_user,
			subscribable_type: "Location"
		)
		@org_subs = Subscription.where(
			user: current_user,
			subscribable_type: "Organisation"
		)
	end

	def edit_profile
		@user = current_user
		@subtitle = "Editing your profile"
		@locations = Location.where(ancestry: nil)
	end

	def update_profile
		begin
			raise BadConfirmation if params[:confirmation] != params[:password]

			@user = current_user()

			@user.real_name = params[:real_name]
			@user.email = params[:email]
			if params[:password].empty? == false
				@user.password = params[:password]
			end
			if params[:home_location_id].blank? == false
				@user.home_location = Location.find params[:home_location_id]
			else
				@user.home_location = nil
			end
			@user.save!
			redirect_to profile_path, flash: {success: "Profile updated"}
		rescue BadConfirmation => e
			@subtitle = "Editing your profile"
			flash.now[:error] = "Bad password confirmation"
			@locations = Location.where(ancestry: nil)
			render :edit_profile, status: :unprocessable_entity
		rescue ActiveRecord::RecordNotFound => e
			@subtitle = "Editing your profile"
			flash.now[:error] = "Home location not found"
			@locations = Location.where(ancestry: nil)
			render :edit_profile, status: :unprocessable_entity
		rescue ActiveRecord::RecordInvalid => e
			@subtitle = "Editing your profile"
			flash.now[:error] = "Invalid Parameters"
			@locations = Location.where(ancestry: nil)
			render :edit_profile, status: :unprocessable_entity
		end
	end

	def request_verification
		address = params[:address] #Snail-Mail

		begin
			throw AlreadyVerified if current_user.verification_code

			@user = current_user()

			@user.verification_code = SecureRandom.hex(4)
			@user.save!

			UserMailer.verification_request(
				@user.user_name,
				@user.real_name,
				@user.verification_code,
				address
			).deliver_later

			redirect_to profile_path, flash: {success: "Request sent"}
		rescue AlreadyVerified => e
			redirect_to profile_path, status: :forbidden,
				flash: {error: "You have already requested to be verified"}
		rescue ActiveRecord::RecordInvalid => e
			redirect_to profile_path, status: :internal_server_error,
				flash: {error: "Could not save verification code"}
		end
	end

	def confirm_verification
		@user = current_user()

		begin
			raise BadConfirmation if params[:code] != @user.verification_code
			raise AlreadyVerified if @user.verified?

			priv = @user.priv
			@user.priv = priv | 0x01
			@user.save!
			redirect_to profile_path, flash: {success: "You are now verified!"}
		rescue BadConfirmation => e
			redirect_to profile_path, flash: {error: "Incorrect code"}
		rescue AlreadyVerified => e
			redirect_to profile_path, flash: {error: "You are already verified"}
		rescue ActiveRecord::RecordInvalid => e
			redirect_to profile_path,
				flash: {error: "Could not save verified status"}
		end
	end

	def delete_profile
		if current_user.id == 1
			redirect_to profile_path, status: :forbidden,
				flash: {error: "Root user can not be deleted"}
		else
			ActionLog.create(json: {
				user_name: current_user.user_name, user_id: current_user.id,
				model: 'user', action: 'delete'
			}).save

			current_user.destroy

			session[:user_id] = nil
			redirect_to root_path,
				flash: {success: "Your account has been deleted"}
		end
	end
end

# vim: ts=4 sts=4 sw=0 noexpandtab

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/edit_profile.html.erb
<%- if @user.errors %>
	<ul class="errors">
		<%- @user.errors.each do |error| %>
		<li><%= error.to_s %></li>
	<%- end %>
	</ul>
<%- end %>

<%= form_with url: profile_path, method: :patch do |f| -%>
	<div class="container">
		<div class="row">
			<%= f.label :real_name, class: 'col-md-2 col-sm-12' -%>
			<%= f.text_field :real_name, value: @user.real_name,
				class: 'col-md-5 col-sm-12'	-%>
		</div>
		<div class="row">
			<%= f.label :email, class: 'col-md-2 col-sm-12' -%>
			<%= f.email_field :email, value: @user.email,
				class: 'col-md-5 col-sm-12' -%>
		</div>
		<div class="row">
			<%= f.label :password, class: 'col-md-2 col-sm-12' -%>
			<%= f.password_field :password, class: 'col-md-5 col-sm-12' -%>
		</div>
		<div class="row">
			<%= f.label :confirmation, class: 'col-md-2 col-sm-12' -%>
			<%= f.password_field :confirmation, class: 'col-md-5 col-sm-12' -%>
		</div>
		<div class="row">
			<%= f.label :home_location_id, "Home location", class: 'col-md-2 col-sm-12' -%>
			<%= f.collection_select(:home_location_id, @locations, :id, :name,
					{include_blank: true, selected: @user.home_location_id},
					{class: 'col-md-5 col-sm-12'}) -%>
		</div>
		<div class="row">
			<%= f.submit "Save", class: 'col-md-5 col-sm-12 offset-md-2' -%>
		</div>
	</div>
<%- end -%>

<%= link_to "Back", profile_path -%>

<%#
	# vim: ts=4 sts=4 sw=0 noexpandtab
-%>

app/views/home/index.html.erb
<div id="map"></div>
<script type="module">
	import {$, useMap, initMap, makeMarker} from "<%= javascript_path "application.js" -%>";

	var src = "<%== @map_source.url -%>";
	var attr = '<%== @map_source.attribution -%>';
	var isVector = <%= @map_source.is_vector -%>;
	var lat = <%= @lat -%>;
	var lng = <%= @lng -%>;
	var zoom = <%= @high_zoom -%>;
	useMap(function(){
		initMap("map", src, attr, isVector, lat, lng, zoom);
		<%- @events.each_key do |loc| -%>
			<%- lat2 = loc.lat %>
			<%- lng2 = loc.lng %>
			<%- str = link_to loc.name, location_path(loc.name), class: :marker_head -%>
			<%- str = str + raw("<ul>") -%>
			<%- @events[loc].each do |ev| -%>
				<%- str = str + raw("<li>") + link_to(ev.name, event_path(ev)) + raw("</li>") -%>
			<%- end -%>
			<%- str = str + raw("</ul>") -%>
			<%= raw "makeMarker(#{lat2}, #{lng2}, '#{str}'" -%>);
		<%- end -%>
		//Re-center as makeMarker unfortunately moves the map arround
		window.map.setView(<%= "[#{@lat}, #{@lng}], #{@high_zoom}" -%>);
	});
</script>

<%-
	# vim: ts=4 sts=4 sw=0 noexpandtab
-%>

app/views/home/profile.html.erb
<div id="info">
	<h2><%= @user.real_name -%></h2>
	<ul>
		<li><b>User Name:</b> <%= @user.user_name -%></li>
		<li><b>Email:</b> <%= @user.email -%></li>
		<li><b>Password:</b> <i>Secret</i></li>
		<%- if @user.home_location -%>
			<li><b>Home Location:</b> <%= @user.home_location.name -%></li>
		<%- else -%>
			<li><b>Home Location:</b> <em>None</em></li>
		<%- end -%>
	</ul>
	<%= link_to "Edit", profile_edit_url -%>
</div>

<h3>Verification</h3>
<div id="verify">
	<%- if @user.verified? -%>
		You are verified!
	<%- elsif @user.verification_code == nil -%>
		<%= form_with url: profile_request_verification_path, method: :post do |f| -%>
			<div class="form-group">
				<%= f.label :address, "Street address" -%>
				<%= f.text_area :address -%>
			</div>
			<%= f.submit -%>
		<%- end -%>
	<%- else -%>
		<%= form_with url: profile_confirm_verification_path, method: :post do |f| -%>
			<div class="form-group">
				<%= f.label :code, "Verification code" -%>
				<%= f.text_field :code -%>
			</div>
			<%= f.submit -%>
		<%- end -%>
	<%- end -%>
</div>

<div id="subscriptions">
	<h3>Subscriptions</h3>

	<h4>Locations</h4>
	<ul><%- @loc_subs.each do |sub| -%>
		<li><%= link_to sub.subscribable.name, location_path(sub.subscribable.name) -%></li>
	<%- end -%></ul>

	<h4>Organisations</h4>
	<ul><%- @org_subs.each do |sub| -%>
		<li><%= link_to sub.subscribable.name, organisation_path(sub.subscribable.name) -%></li>
	<%- end -%></ul>
</div>

<div id="terminate">
	<h2>Terminate</h2>
	<p>If you really want to you can delete your account here.</p>
	<%= form_with url: profile_path, method: :delete, onsubmit: "return confirm('Are you sure?');" do |f| -%>
		<div class="form-group">
			<label for="confirm_1">I want to delete my profile, the comments
				that I have left on all event pages and the event pages I have
				created.</label>
			<input type="checkbox" id="confirm_1" name="confirm_1" value=false />
			<script type="module">
				import {$, toggleSubmit} from "<%= javascript_path "application.js" -%>";

				$("#confirm_1").change( function(){
					toggleSubmit("#delete_btn");
				});
			</script>
		</div>
		<%= f.submit "Delete my account", disabled: true, id: :delete_btn -%>
	<%- end -%>
</div>

<%-
	# vim: ts=4 sts=4 sw=0 noexpandtab
-%>