config/routes.rb
Rails.application.routes.draw do
	concern :commentable do
		post '/comments' => :create_comment, as: :comments
		delete '/commments/:id' => :destroy_comment, as: :comment
	end

	concern :subscribable do
		get :subscribe
		get :unsubscribe
	end

	root "meta#index"
	scope controller: :meta do
		get '/about' => :about
		get '/contact' => :contact
		get '/terms' => :terms
	end

	scope controller: :session do
		get '/signup' => :signup
		post '/register' => :register
		get '/login' => :login
		post '/authenticate' => :authenticate
		get '/logout' => :logout
		get '/forgot-password' => :forgot_password
		post '/password-reset-request' => :password_reset_request
		get '/password-reset/:sgid' => :password_reset, as: :password_reset
		post '/password-reset/:sgid' => :submit_password_reset
		get '/password-reset-sent' => :password_reset_sent
	end

	scope controller: :home do
		get '/home' => :index
		get '/profile' => :profile
		post '/profile/request_verification' => :request_verification
		post '/profile/confirm_verification' => :confirm_verification
		get '/profile/edit' => :edit_profile
		patch '/profile' => :update_profile
		delete '/profile' => :delete_profile
	end

	resources :locations, param: :name, only: [:index, :show] do
		concerns :subscribable
	end

	resources :events do
		concerns :commentable
	end

	resources :organisations, param: :name do
		concerns :subscribable
		get 'moderators' => :choose_moderators
		post 'moderators' => :update_moderators
		get :apply
		get :leave
		get :invite_members
		post :send_invitations
		get :transfer
		post :begin_transfer
		resources :discussions do
			concerns :commentable
		end
	end

	#Passing registrant status to another user
	get '/organisations/:org_sgid/:user_sgid/accept-transfer' => "organisations#accept_transfer", as: :organisation_accept_transfer
	get '/organisations/:org_sgid/:user_sgid/reject-transfer' => "organisations#reject_transfer", as: :organisation_reject_transfer

	#User applied for membership
	get '/memberships/:sgid/accept_application' => "memberships#accept_application", as: :membership_accept_application
	get '/memberships/:sgid/reject_application' => "memberships#reject_application", as: :membership_reject_application

	#User offerred membership
	get '/memberships/:org_sgid/:user_sgid/accept-invitation' => "memberships#accept_invitation", as: :membership_accept_invitation
	get '/memberships/:org_sgid/:user_sgid/reject-invitation' => "memberships#reject_invitation", as: :membership_reject_invitation

	scope controller: :feedback do
		get '/feedback' => :index
		get '/feedback/general' => :general
		get '/feedback/missing_location' => :location
		post '/feedback/general' => :submit_general
		post '/feedback/missing_location' => :submit_location
	end

	namespace :console, controller: :main do
		root "main#index"

		resources :users
		resources :locations do
			post 'from_csv', on: :collection
			get 'to_csv', on: :collection
		end
		resources :events
		resources :organisations

		get 'config' => :config_index
		get 'config/branding' => :branding
		post 'config/branding' => :update_branding
		post 'config/logo' => :update_logo
		get 'config/map' => :map
		post 'config/map' => :update_map
		get 'config/terms' => :terms
		post 'config/terms' => :update_terms
		get 'config/export' => :export_config
		post 'config/import' => :import_config

		get 'logs/:hours/hours' => :logs, as: 'logs'

		get 'announcement' => :announcement
		post 'announcement' => :submit_announcement
	end
end

# vim: ts=4 sts=4 sw=0 noexpandtab

app/controllers/console/events_controller.rb
module Console

class EventsController < ApplicationController
	include EventsConcern
	layout "console"
	before_action :is_admin_check

	def index
		@subtitle = "Events"
		@pagy, @events = pagy(Event.all)
	end

	def new
		@subtitle = "Create event"
		@event = Event.new

		@event.start_time = default_start_time()
		@event.end_time = default_end_time()
		@locations = Location.all.order(:name)
		@users = User.all.order(:user_name)
		@organisations = Organisation.all.order(:name)
	end

	def create
		begin
			@event = Event.new

			@event.name = params[:name]
			@event.descr = params[:descr]
			@event.start_time = parse_time(params[:event][:start_time])
			@event.end_time = parse_time(params[:event][:end_time])
			@event.user_id = params[:user_id]
			@event.location_id = params[:location_id]
			if params[:event][:organisation_id].empty? == false
				@event.organisation = Organisation.find(
					params[:event][:organisation_id]
				)
			else
				@event.organisation = nil
			end

			@event.save!
			redirect_to console_event_path(@event),
				flash: {success: "Event created"}

		rescue Date::Error => e
			@subtitle = "Create event"
			flash.now[:error] = "Invalid time or date"
			@event.start_time = default_start_time()
			@event.end_time = default_end_time()
			@locations = Location.all.order(:name)
			@users = User.all.order(:user_name)
			@organisations = Organisation.all.order(:name)
			render :new, status: :unprocessable_entity
		rescue IOError => e
			@subtitle = "Create Event"
			@locations = Location.all.order(:name)
			@users = User.all.order(:user_name)
			@organisations = Organisation.all.order(:name)
			flash.now[:error] = "User is not a member of organisation"
			render :new, status: :unprocessable_entity
		rescue ActiveRecord::RecordInvalid => e
			@subtitle = "Create event"
			@locations = Location.all.order(:name)
			@users = User.all.order(:user_name)
			@organisations = Organisation.all.order(:name)
			flash.now[:error] = "Invalid parameters"
			render :new, status: :unprocessable_entity
		end
	end

	def show
		begin
			@event = Event.find params[:id]
			@subtitle = @event.name
		rescue ActiveRecord::RecordNotFound => e
			redirect_to console_events_path,
				flash: {error: "Could not find event"}
		end
	end

	def edit
		begin
			@event = Event.find params[:id]
			@subtitle = "Editing #{@event.name}"
			@locations = Location.all.order(:name)
			@users = User.all.order(:user_name)
			@organisations = Organisation.all.order(:name)
		rescue ActiveRecord::RecordNotFound => e
			redirect_to console_events_path,
				flash: {error: "Could not find event"}
		end
	end

	def update
		begin
			@event = Event.find params[:id]

			@event.name = params[:event][:name]
			@event.descr = params[:event][:descr]
			@event.start_time = parse_time(params[:event][:start_time])
			@event.end_time = parse_time(params[:event][:end_time])
			@event.user_id = params[:event][:user_id]
			@event.location_id = params[:event][:location_id]
			if params[:event][:organisation_id].empty? == false
				@event.organisation = Organisation.find(
					params[:event][:organisation_id]
				)
			else
				@event.organisation = nil
			end

			@event.save!
			redirect_to console_event_path(@event),
				flash: {success: "Event updated"}
		rescue ActiveRecord::RecordNotFound => e
			@subtitle = "Editing #{@event.name}"
			redirect_to console_events_path,
				flash: {error: "Could not find event"}
		rescue Date::Error => e
			@subtitle = "Editing #{@event.name}"
			@locations = Location.all.order(:name)
			@users = User.all.order(:user_name)
			@organisations = Organisation.all.order(:name)
			flash.now[:error] = "Invalid time or date"
			render :edit, status: :unprocessable_entity
		rescue IOError => e
			@subtitle = "Create Event"
			@locations = Location.all.order(:name)
			@users = User.all.order(:user_name)
			@organisations = Organisation.all.order(:name)
			flash.now[:error] = "User is not a member of organisation"
			render :new, status: :unprocessable_entity
		rescue ActiveRecord::RecordInvalid => e
			@subtitle = "Editing #{@event.name}"
			@locations = Location.all.order(:name)
			@users = User.all.order(:user_name)
			@organisations = Organisation.all.order(:name)
			flash.now[:error] = "Invalid parameters"
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		begin
			event = Event.find params[:id]

			event.destroy!
			redirect_to console_events_path, flash: {success: "Event deleted"}
		rescue ActiveRecord::RecordNotFound => e
			redirect_to console_events_path,
				flash: {error: "Could not find event"}
		rescue ActiveRecord::RecordNotDestroyed => e
			@subtitle = @event.name
			flash.now[:error] = "Could not delete event"
			render :show, status: :internal_server_error
		end
	end
end

end

# vim: ts=4 sts=4 sw=0 noexpandtab

app/controllers/console/locations_controller.rb
require 'csv'


module Console

class LocationsController < ApplicationController
	layout "console"
	before_action :is_admin_check

	def index
		@subtitle = "Locations"

		@locations = Location.where(ancestry: nil).order(:name)
	end

	def new
		@subtitle = "Create Location"

		@locations = Location.all.order(:name)
		@location = Location.new
	end

	def create
		begin
			@location = Location.new
			@location.name = params[:name]
			@location.descr = params[:descr]
			@location.parent_id = params[:parent_id]
			@location.address = params[:address]
			@location.lat = params[:lat]
			@location.lng = params[:lng]

			@location.save!

			redirect_to console_location_path(@location),
				flash: {success: "Location created"}
		rescue ActiveRecord::RecordInvalid => e
			@subtitle = "Create Location"
			@locations = Location.all.order(:name)
			flash.now[:error] = "Invalid parameters"
			render :new, status: :unprocessable_entity
		end
	end

	def show
		begin
			@location = Location.find params[:id]
			@subtitle = @location.name
		rescue ActiveRecord::RecordNotFound => e
			redirect_to console_locations_path,
				flash: {error: "Could not find location"}
		end
	end

	def edit
		begin
			@location = Location.find params[:id]
			@locations = Location.all.order(:name)
			@subtitle = "Editing #{@location.name}"
		rescue ActiveRecord::RecordNotFound => e
			redirect_to console_locations_path,
				flash: {error: "Could not find location"}
		end
	end

	def update
		begin
			@location = Location.find params[:id]

			@location.name = params[:name]
			@location.descr = params[:descr]
			@location.parent_id = params[:parent_id]
			@location.address = params[:address]
			@location.lat = params[:lat]
			@location.lng = params[:lng]

			@location.save!

			redirect_to console_location_path(@location),
				flash: {success: "Location updated"}
		rescue ActiveRecord::RecordNotFound => e
			redirect_to console_locations_path,
				flash: {error: "Could not find location"}
		rescue ActiveRecord::RecordInvalid => e
			@subtitle = "Editing #{@location.name}"
			@locations = Location.all.order(:name)
			flash.now[:error] = "Invalid parameters"
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		begin
			@location = Location.find params[:id]

			@location.destroy!

			redirect_to console_locations_path,
				flash: {success: "Location deleted"}
		rescue ActiveRecord::RecordNotFound => e
			redirect_to console_locations_path,
				flash: {error: "Could not find location"}
		rescue ActiveRecord::RecordNotDestroyed => e
			@subtitle = @location.name
			flash.now[:error] = "Could not delete location"
			render :show, status: :internal_server_error
		end
	end

	def to_csv
		attributes = %w{id name ancestry descr address lat lng}

		data = CSV.generate do |csv|
			Location.order(:id).each do |loc|
				csv << attributes.map{|attr| loc.send attr}
			end
		end

		send_data data, filename: 'locations.csv'
	end

	def from_csv
		locs = CSV.parse(params[:file].tempfile)

		User.all.update(home_location_id: nil)

		Location.destroy_all

		locs.each{|l| Location.create(id: l[0],
									  name: l[1],
									  ancestry: l[2],
									  descr: l[3],
									  address: l[4],
									  lat: l[5],
									  lng: l[6])}

		#Reset primary key
		connection = ActiveRecord::Base.connection
		connection.execute("SELECT setval(pg_get_serial_sequence('locations', 'id'), MAX(id)) FROM locations;")

		redirect_to console_locations_path
	end
end

end

# vim: ts=4 sts=4 sw=0 noexpandtab

app/controllers/console/main_controller.rb
require 'yaml'

module Console

class MainController < ApplicationController
	layout "console"
	before_action :is_admin_check

	def index
		@subtitle = "Home"

		@userCount = User.count
		@locationCount = Location.count
		@eventCount = Event.count
	end

	def config_index
		@subtitle = "Configuration"
	end

	def branding
		@subtitle = "Branding Configuration"
	end

	def update_branding
		Rails.configuration.vicinitude[:site_name] = params[:site_name]
		Rails.configuration.vicinitude[:town_name] = params[:town_name]
		Rails.configuration.vicinitude[:admin_email] = params[:admin_email]
		Rails.configuration.vicinitude[:domain_name] = params[:domain_name]
		Rails.configuration.vicinitude[:notice] = params[:notice]
		Rails.configuration.vicinitude[:footer_message] = params[:footer_message]

		save_config!

		redirect_to console_config_branding_path,
			flash: {success: "Configuration updated"}
	end

	def update_logo
		if params[:logo_32px]
			file = File.open('app/assets/images/logo_32px.png', 'wb')
			file << params[:logo_32px].read
			file.close
		end

		if params[:logo_64px]
			file = File.open('app/assets/images/logo_64px.png', 'wb')
			file << params[:logo_64px].read
			file.close
		end

		if params[:logo_200px]
			file = File.open('app/assets/images/logo_200px.png', 'wb')
			file << params[:logo_200px].read
			file.close
		end

		redirect_to console_config_branding_path,
			flash: {success: "Logo updated"}
	end

	def map
		@subtitle = "Map Configuration"
		@map_sources = MapSource.all.order(:id)
		@current_source = Rails.configuration.vicinitude[:map_source]
	end

	def update_map
		Rails.configuration.vicinitude[:map_source] = params[:source_id]
		if params[:source_url] and params[:source_is_vector]
			custom_source = MapSource.find(1)
			custom_source.url = params[:source_url]
			custom_source.is_vector = params[:source_is_vector]
			custom_source.attribution = params[:source_attribution]
			custom_source.save
		end
		Rails.configuration.vicinitude[:map_centre][:lat] = params[:lat]
		Rails.configuration.vicinitude[:map_centre][:lng] = params[:lng]
		Rails.configuration.vicinitude[:map_centre][:high_zoom] = params[:high_zoom]
		Rails.configuration.vicinitude[:map_centre][:low_zoom] = params[:low_zoom]

		save_config!

		redirect_to console_config_map_path,
			flash: {success: "Configuration updated"}
	end

	def terms
		@subtitle = "Terms of Service Configuration"
	end

	def update_terms
		Rails.configuration.vicinitude[:terms] = params[:terms]

		save_config!

		redirect_to console_config_terms_path,
			flash: {success: "Terms of Service updated"}
	end

	def export_config
		send_file 'config/vicinitude.yml'
	end

	def import_config
		yaml = YAML.load(params[:file].read)[:shared]

		Rails.configuration.vicinitude[:site_name] = yaml[:site_name]
		Rails.configuration.vicinitude[:town_name] = yaml[:town_name]
		Rails.configuration.vicinitude[:admin_email] = yaml[:admin_email]
		Rails.configuration.vicinitude[:domain_name] = yaml[:domain_name]
		Rails.configuration.vicinitude[:notice] = yaml[:notice]
		Rails.configuration.vicinitude[:footer_message] = yaml[:footer_message]

		Rails.configuration.vicinitude[:map_source] = yaml[:map_source]
		Rails.configuration.vicinitude[:map_centre][:lat] = yaml[:map_centre][:lat]
		Rails.configuration.vicinitude[:map_centre][:lng] = yaml[:map_centre][:lng]
		Rails.configuration.vicinitude[:map_centre][:high_zoom] = yaml[:map_centre][:high_zoom]
		Rails.configuration.vicinitude[:map_centre][:low_zoom] = yaml[:map_centre][:low_zoom]

		Rails.configuration.vicinitude[:terms] = yaml[:terms]

		save_config!

		redirect_to console_config_path,
			flash: {success: "Configuration updated"}
	end

	def logs
		@hours = params[:hours].to_i
		now = Time.now
		@action_logs = ActionLog.where("created_at > '#{now - @hours.hours}'")
		@subtitle = "User actions in the last #{@hours} hours"
	end

	def announcement
		@subtitle = "Announcement to users"
	end

	def submit_announcement
		User.all.each do |user|
			AnnouncementMailer.general_announcement(
				user,
				params[:subject],
				params[:body]
			).deliver_later
		end

		redirect_to console_root_path,
			flash: {success: "Your announcement has been made"}
	end

	#TODO Figure out how best this could trigger an error condition
	private def save_config!
		yaml = {
			shared: {
				site_name: Rails.configuration.vicinitude[:site_name],
				town_name: Rails.configuration.vicinitude[:town_name],
				admin_email: Rails.configuration.vicinitude[:admin_email],
				domain_name: Rails.configuration.vicinitude[:domain_name],
				notice: Rails.configuration.vicinitude[:notice],
				footer_message: Rails.configuration.vicinitude[:footer_message],
				map_source: Rails.configuration.vicinitude[:map_source],
				map_centre: {
					lat: Rails.configuration.vicinitude[:map_centre][:lat],
					lng: Rails.configuration.vicinitude[:map_centre][:lng],
					high_zoom: Rails.configuration.vicinitude[:map_centre][:high_zoom],
					low_zoom: Rails.configuration.vicinitude[:map_centre][:low_zoom]
				},
				terms: Rails.configuration.vicinitude[:terms]
			}
		}.to_yaml

		file = File.open("config/vicinitude.yml", "w")
		file.write yaml
		file.close
	end
end

end

# vim: ts=4 sts=4 sw=0 noexpandtab

app/helpers/console_helper.rb
module ConsoleHelper
end

app/views/console/locations/_location_form.html.erb
<script type="module">
	import {initRichTextEditor} from "<%= javascript_path "application" -%>";
	initRichTextEditor();
</script>

<%- path = @location.id ? console_location_path(@location) : console_locations_path -%>
<%- method = @location.id ? "patch" : "post" -%>
<%= form_with url: path, method: method do |f| -%>
	<div class="container">
		<div class="row">
			<%= f.label :name, class: 'col-2' -%>
			<%= f.text_field :name, value: @location.name, class: 'col-5' -%>
		</div>
		<div class="row">
			<%- @location.errors.full_messages_for(:name).each do |message| -%>
				<div><%= message -%></div>
			<%- end -%>
		</div>

		<div class="row">
			<%= f.label :descr, "Description", class: 'col-2' -%>
			<%= f.hidden_field :descr, value: @location.descr -%>
			<div class="col-5">
				<trix-editor input="locaton_descr"></trix-editor>
			</div>
		</div>

		<div class="row">
			<%= f.label :parent_id, "Located in", class: 'col-2' -%>
			<%= f.collection_select :parent_id, @locations, :id, :name,
				{include_blank: "---"}, class: 'col-5' -%>
		</div>
		<div class="row">
			<%- @location.errors.full_messages_for(:parent_id).each do |message| -%>
				<div><%= message -%></div>
			<%- end -%>
		</div>

		<div class="row">
			<%= f.label :address, class: 'col-2' -%>
			<%= f.text_area :address, value: @location.address, rows: 5,
				class: 'col-5' -%>
		</div>
		<div class="row">
			<%- @location.errors.full_messages_for(:address).each do |message| -%>
				<div><%= message -%></div>
			<%- end -%>
		</div>

		<div class="row">
			<%= f.label :lat, "Lattitude", class: 'col-2' -%>
			<%= f.number_field :lat, step: 0.00001, value: @location.lat,
				class: 'col-5' -%>
		</div>
		<div class="row">
			<%- @location.errors.full_messages_for(:lat).each do |message| -%>
				<div><%= message -%></div>
			<%- end -%>
		</div>

		<div class="row">
			<%= f.label :lng, "Longitude", class: 'col-2' -%>
			<%= f.number_field :lng, step: 0.00001, value: @location.lng,
				class: 'col-5' -%>
		</div>
		<div class="row">
			<%- @location.errors.full_messages_for(:lng).each do |message| -%>
				<div><%= message -%></div>
			<%- end -%>
		</div>

		<div class="row">
			<%= f.submit "Save", class: 'col-5 offset-2' -%>
		</div>
	</div>
<%- end -%>

<%
	# vim: ts=4 sts=4 sw=0 noexpandtab
%>

app/views/console/locations/_location_tree.html.erb
<ul><%- locations.order(:name).each do |loc| -%>
	<li><%= link_to loc.name, console_location_path(loc) -%></li>
	<%- if loc.has_children? -%>
		<%= render partial: 'location_tree', locals:
			{locations: loc.children.order(:name)} -%>
	<%- end -%>
<%- end -%></ul>

<%
	# vim: ts=4 sts=4 sw=0 noexpandtab
%>

app/views/console/locations/edit.html.erb
<%= render partial: 'location_form' -%>

<p>
	<%= link_to "Back", console_location_path(@location) -%>
</p>

<%
	# vim: ts=4 sts=4 sw=0 noexpandtab
%>

app/views/console/locations/index.html.erb
<p>
	<%= link_to "New", new_console_location_path -%>
</p>

<p>
	<%= render partial: 'location_tree', locals: {locations: @locations} -%>
</p>

<h3>Export Locations</h3>
<%= form_with url: to_csv_console_locations_path, method: :get do |f| -%>
	<div class="container">
		<div class="row">
			<%= f.label :submit, "CSV File", class: 'col-2' -%>
			<%= f.submit "Download", class: 'col-5' -%>
		</div>
	</div>
<%- end -%>

<h3>Import Locations</h3>
<p><strong>WARNING:</strong> This feature exist for setting up new
	installations. It will delete all existing events and event comments.</p>
<%= form_with url: from_csv_console_locations_path do |f| -%>
	<div class="container">
		<div class="row">
			<%= f.label :confirm_1, "There is no data at-risk",
				class: 'col-2' -%>
			<%= f.check_box :confirm_1, value: false,
				class: 'col-5' -%>
		</div>
		<script type="module">
			import {$, toggleSubmit} from "<%= javascript_path "application.js" -%>";

			$("#confirm_1").change( function(){
				toggleSubmit("#from_csv_btn");
			});
		</script>
		<div class="row">
			<%= f.label :file, class: 'col-2' -%>
			<%= f.file_field :file, class: 'col-5' -%>
		</div>
		<div class="row">
			<%= f.submit disabled: true, id: :from_csv_btn,
				class: 'col-5 offset-2' -%>
		</div>
	</div>
<%- end -%>

<%
	# vim: ts=4 sts=4 sw=0 noexpandtab
%>

app/views/console/locations/new.html.erb
<%= render partial: 'location_form' %>

<p>
	<%= link_to "Back", console_locations_path -%>
</p>

<%
	# vim: ts=4 sts=4 sw=0 noexpandtab
%>

app/views/console/locations/show.html.erb
<p>
	<b>Address:</b>
	<pre class="text-display"><%= @location.address -%></pre>
</p>
<p>
	<b>Located in:</b>
	<%- if @location.has_parent? -%>
		<%= link_to @location.parent.name, console_location_path(@location.parent) -%>
	<%- end -%>
</p>
<p>
	<b>Lattitude & Longitude:</b>
	<%= @location.lat -%>, <%= @location.lng -%>
</p>

<p>
	<b>Description:</b>
	<div class="text-display">
		<%== sanitize @location.descr -%>
	</div>
</p>

<p>
	<%= button_to "Edit", edit_console_location_path(@location), method: :get -%>
	<%= button_to "Delete", console_location_path(@location), method: :delete -%>
</p>

<p>
	<%= link_to "Back", console_locations_path -%>
</p>


<%
	# vim: ts=4 sts=4 sw=0 noexpandtab
%>